# Generated by Django 2.2.8 on 2020-10-13 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateField(auto_created=True)),
                ('tarefa', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('feito', models.BooleanField(default=False)),
                ('slug', models.SlugField(max_length=200)),
                ('atualizado_em', models.DateField(auto_now=True)),
            ],
        ),
    ]
