# Generated by Django 2.2.8 on 2020-10-13 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='criado_em',
            field=models.DateField(auto_now_add=True),
        ),
    ]
