# Generated by Django 3.1.2 on 2020-10-13 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20201013_0533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='tarefa',
            field=models.CharField(error_messages={'unique': 'Tarefa já existente.'}, max_length=200, unique=True),
        ),
    ]
