# Generated by Django 3.1.2 on 2020-10-28 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20201013_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='feito',
            field=models.IntegerField(default=0),
        ),
    ]
